/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_usc_ulord_hello_CryptoHelloContext */

#ifndef _Included_co_usc_ulord_hello_CryptoHelloContext
#define _Included_co_usc_ulord_hello_CryptoHelloContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_usc_ulord_hello_CryptoHelloContext
 * Method:    helloHash
 * Signature: (Ljava/lang/String;JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_co_usc_ulord_hello_CryptoHelloContext_helloHash
  (JNIEnv *, jclass, jstring, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
